feature/ Past Groups
makeadiff/Phoenix pull request #60
Opened 2021-07-13 15:28 UTC by Bhanu-mbvg

Fixes #51 

- [ ] REST API -> /users/1/past_groups
- [ ] Graphql Version  -> { user(id: 1) { past_groups { id name year }} }

2021-07-20 05:56 UTC, binnyva commented on api/swagger/swagger.yaml
> +          required: given_to_user_name
This is a `true` / `false`

2021-07-20 05:59 UTC, binnyva commented on graphql-schema/schema.graphql
> +type PastGroups {
I am thinking a better way of doing this is just adding a `year` field to the `Group` type. Adding a new type might not be required.

2021-07-20 06:00 UTC, binnyva commented on graphql-schema/schema.graphql
> +    past_groups: [PastGroups] @hasMany(relation: "pastGroups")
`past_groups: [Group]  @hasMany(relation: "pastGroups")`
Might be a better/simpler option.

2021-07-20 06:02 UTC, binnyva requested changes
This is pretty good. Some minor changes requested :-D

2021-07-21 07:09 UTC, Bhanu-mbvg commented
@Bhanu-mbvg made the requested changes

2021-07-22 08:16 UTC, merged